package rotas

import (
	"backend/src/controllers"
	"net/http"
)

// Rotas admin: gestão de acervo e moderação (prefixo /admin).
var rotasAdmin = []Rota{
	{
		URI:                "/admin/usuarios",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminBuscarUsuarios,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/usuarios",
		Metodo:             http.MethodPost,
		Funcao:             controllers.AdminCriarUsuario,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/usuarios/{usuarioId}",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminBuscarUsuarioPorID,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/usuarios/{usuarioId}",
		Metodo:             http.MethodPut,
		Funcao:             controllers.AdminAtualizarUsuario,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/usuarios/{usuarioId}",
		Metodo:             http.MethodDelete,
		Funcao:             controllers.AdminInativarUsuario,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/livros",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminListarLivros,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/livros",
		Metodo:             http.MethodPost,
		Funcao:             controllers.CriarLivro,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/livros/{id}",
		Metodo:             http.MethodGet,
		Funcao:             controllers.BuscarLivroPorID,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/livros/{id}",
		Metodo:             http.MethodPut,
		Funcao:             controllers.AtualizarLivro,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/livros/{id}",
		Metodo:             http.MethodDelete,
		Funcao:             controllers.InativarLivro,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/categorias",
		Metodo:             http.MethodGet,
		Funcao:             controllers.BuscarCategorias,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/categorias",
		Metodo:             http.MethodPost,
		Funcao:             controllers.CriarCategoria,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/categorias/{id}",
		Metodo:             http.MethodGet,
		Funcao:             controllers.BuscarCategoriaPorID,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/categorias/{id}",
		Metodo:             http.MethodPut,
		Funcao:             controllers.AtualizarCategoria,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/categorias/{id}",
		Metodo:             http.MethodDelete,
		Funcao:             controllers.InativarCategoria,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/comentarios",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioComentarios,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/livros",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioLivros,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/seguidores-seguindo",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioSeguidoresSeguindo,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/historico-leitura",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioHistoricoLeitura,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/usuarios",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFUsuarios,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/avaliacoes",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFAvaliacoes,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/assinaturas",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFAssinaturas,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/denuncias",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFDenuncias,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/comentarios",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFComentarios,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/livros",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFLivros,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/seguidores-seguindo",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFSeguidoresSeguindo,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/relatorios/pdf/historico-leitura",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminRelatorioPDFHistoricoLeitura,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/denuncias",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminListarDenuncias,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/denuncias/{id}",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminBuscarDenunciaPorID,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/denuncias/{id}",
		Metodo:             http.MethodPatch,
		Funcao:             controllers.AdminResolverDenuncia,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/templates",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminListarTemplates,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/templates",
		Metodo:             http.MethodPost,
		Funcao:             controllers.AdminCriarTemplate,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/templates/{id}",
		Metodo:             http.MethodGet,
		Funcao:             controllers.AdminBuscarTemplatePorID,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/templates/{id}",
		Metodo:             http.MethodPut,
		Funcao:             controllers.AdminAtualizarTemplate,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
	{
		URI:                "/admin/templates/{id}",
		Metodo:             http.MethodDelete,
		Funcao:             controllers.AdminExcluirTemplate,
		RequerAutenticacao: true,
		RequerAdmin:        true,
	},
}
